name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./  # Root directory where your static files are located

